name: linux
on: [push, pull_request]
jobs:

  build:
    name: build
    runs-on: [ ubuntu-20.04 ]
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Install mbedTLS
      run: sudo apt-get install libmbedtls-dev

    - name: Install meson
      run: sudo apt-get install meson

    - name: Configure
      run: meson build -Dnng_tls=true

    - name: Build
      run: cd build && ninja

    - name: Test
      run: cd build && meson test --print-errorlogs
