name: sanitize
on: [push, pull_request]
jobs:
  sanitize:
    env:
      CC: clang
      CXX: clang++
      CTEST_OUTPUT_ON_FAILURE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        sanitizer: [ address, undefined, thread ]
        os: [ ubuntu-20.04 ]

    steps:
      - uses: actions/checkout@v1

      - uses: mstksg/get-package@v1
        with:
            apt-get: meson libmbedtls-dev
            brew: ninja mbedtls

      - name: Configure
        run: meson build -Dbuildtype=debug -Db_sanitize=${{ matrix.sanitizer }} -Dnng_tls=true -Dnng_tools=false

      - name: Build
        run: cd build && ninja

      - name: Test
        run: cd build && meson test --print-errorlogs
