name: windows
on: [push, pull_request]
jobs:

  build:
    name: build
    runs-on: [ windows-latest ]
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Configure
      run: meson build

    - name: Build
      run: meson compile -C build

    - name: Test
      run: meson test -C build --print-errorlogs
